# Site settings
title: Jenny Plunkett
email: jenny@jennyplunkett.me
description: > # this means to ignore newlines until "baseurl:"
  Jenny Plunkett
baseurl: "" # the subpath of your site, e.g. /blog/
url: "jennyplunkett.me" # the base hostname & protocol for your site
markdown: redcarpet
highlighter: pygments
paginate: 5
paginate-path: "/page:num"