# Site settings
title: Jenny Plunkett
description: ""
url: "http://www.jennyplunkett.me"
author:
  name: "Jenny Plunkett"
  email: "jenny@jennyplunkett.me"
  url: "http://www.jennyplunkett.me"

# Build settings
baseurl: / # Change this to your relative path (ex: /blog/), or leave just a /
markdown: kramdown
source: .
destination: ./_site
permalink: /:title
paginate: 8
paginate_path: /page:num/

# Default values
defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"

# Custom variables
version: "1.1.0"

# Options
custom_header: false
custom_nav_footer: false
reverse: false
