# Setup
title:               Jenny Plunkett
tagline:             'The University of Texas at Austin'
description:         "BS Computer Engineering, The University of Texas at Austin"
url:                 jennyplunkett.me
baseurl:             ''
gems:                [jekyll-paginate]
paginate:            5
paginate_path:       "/page:num/"
excerpt_separator:   ""
post_dirs:           false
permalink:           pretty

# About/contact
author:
  name:              Jenny Plunkett
  email:             jenny@jennyplunkett.me
