# Setup
title:               Jenny Plunkett
tagline:             'The University of Texas at Austin, Class of 2017'
description:         "BS Computer Engineering, The University of Texas at Austin, Class of 2017"
url:                 jennyplunkett.me
baseurl:             ''
paginate:            5
permalink: /:categories/:title
excerpt_separator: ""

# About/contact
author:
  name:              Jenny Plunkett
  email:             jenny@jennyplunkett.me
